databases:
  - name: Are_You_Busy
    databaseName: Are_You_Busy
    user: TakenakaEri
    plan: free

services:
  - type: web
    name: Are_You_Busy
    runtime: ruby
    plan: free
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: Are_You_Busy
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false

